name: Branch name validation

on:
  push:

jobs:
  valid-branch-name:
    runs-on: ubuntu-24.04

    steps:

    - name: Verify branch name
      run: |
        if ! [[ "$GITHUB_REF_NAME" =~ ^feature/.*|^features/.*|^fix/.*|^release/.*|^doc/.*|develop|^issue-*|^dependabot/* ]]; then
            exit 1
        fi
