name: Publish docker images
on:
  push:
    branches:
      - 'docker/*'
      - dependabot/*
      - fix/try-ubuntu24-ci

jobs:
  docker_publish:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Docker file push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: antaresrte/rte-antares
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: docker
        dockerfile: centos7-basic-requirements
        cache: true
        tags: centos7-simulator-no-deps
